"""Adding vehicles

Revision ID: 30132ebd6c37
Revises: 9557af8a711b
Create Date: 2020-06-07 13:02:05.811532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "30132ebd6c37"
down_revision = "9557af8a711b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vehicle",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=10), nullable=True),
        sa.Column("name", sa.String(length=64), nullable=True),
        sa.Column("num_wagons", sa.Integer(), nullable=True),
        sa.Column("age", sa.Integer(), nullable=True),
        sa.Column("remaining_life", sa.Integer(), nullable=True),
        sa.Column("speed", sa.Integer(), nullable=True),
        sa.Column("state", sa.Integer(), nullable=True),
        sa.Column("running_cost", sa.BigInteger(), nullable=True),
        sa.Column("profit_this_year", sa.BigInteger(), nullable=True),
        sa.Column("profit_last_year", sa.BigInteger(), nullable=True),
        sa.Column("value", sa.BigInteger(), nullable=True),
        sa.Column("road_type", sa.Integer(), nullable=True),
        sa.Column("length", sa.Float(), nullable=True),
        sa.Column("group_id", sa.Integer(), nullable=True),
        sa.Column("is_articulated", sa.Boolean(), nullable=True),
        sa.Column("has_shared_orders", sa.Boolean(), nullable=True),
        sa.Column("reliability", sa.Float(), nullable=True),
        sa.Column("maximum_order_distance", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "vehicle_timescale",
        sa.Column("vehicle_id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("running_cost", sa.Integer(), server_default="0", nullable=False),
        sa.Column("profit_this_year", sa.Integer(), server_default="0", nullable=False),
        sa.Column("value", sa.Integer(), server_default="0", nullable=False),
        sa.Column("reliability", sa.Integer(), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(["vehicle_id"], ["vehicle.id"],),
        sa.PrimaryKeyConstraint("vehicle_id", "timestamp"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("vehicle_timescale")
    op.drop_table("vehicle")
    # ### end Alembic commands ###
