"""Adding towns

Revision ID: 4c549805cdab
Revises: 2af7ba66f3dd
Create Date: 2020-06-07 17:23:27.451648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4c549805cdab"
down_revision = "2af7ba66f3dd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "town",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=True),
        sa.Column("population", sa.Integer(), nullable=True),
        sa.Column("house_count", sa.Integer(), nullable=True),
        sa.Column("location", sa.Integer(), nullable=True),
        sa.Column("growth_rate", sa.Integer(), nullable=True),
        sa.Column("is_city", sa.Boolean(), nullable=True),
        sa.Column("last_updated", sa.Date(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "town_timescale",
        sa.Column("town_id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("population", sa.Integer(), server_default="0", nullable=False),
        sa.Column("house_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("growth_rate", sa.Integer(), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(["town_id"], ["town.id"],),
        sa.PrimaryKeyConstraint("town_id", "timestamp"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("town_timescale")
    op.drop_table("town")
    # ### end Alembic commands ###
