"""Adding even more stats

Revision ID: 6e29dea99a25
Revises: e1d4880587b7
Create Date: 2020-06-06 17:36:41.492323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6e29dea99a25"
down_revision = "e1d4880587b7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "company",
        sa.Column("current_loan", sa.BigInteger(), server_default="0", nullable=True),
    )
    op.add_column(
        "company",
        sa.Column("delivered", sa.BigInteger(), server_default="0", nullable=True),
    )
    op.add_column(
        "company",
        sa.Column("income", sa.BigInteger(), server_default="0", nullable=True),
    )
    op.add_column(
        "company",
        sa.Column("money", sa.BigInteger(), server_default="0", nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("company", "money")
    op.drop_column("company", "income")
    op.drop_column("company", "delivered")
    op.drop_column("company", "current_loan")
    # ### end Alembic commands ###
