"""Timescale Addition

Revision ID: 9557af8a711b
Revises: 6e29dea99a25
Create Date: 2020-06-06 18:09:55.655342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9557af8a711b"
down_revision = "6e29dea99a25"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "company_timescale",
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("num_train", sa.Integer(), server_default="0", nullable=False),
        sa.Column("num_lorry", sa.Integer(), server_default="0", nullable=False),
        sa.Column("num_plane", sa.Integer(), server_default="0", nullable=False),
        sa.Column("num_ship", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "num_train_stations", sa.Integer(), server_default="0", nullable=False
        ),
        sa.Column(
            "num_lorry_stations", sa.Integer(), server_default="0", nullable=False
        ),
        sa.Column(
            "num_plane_stations", sa.Integer(), server_default="0", nullable=False
        ),
        sa.Column(
            "num_ship_stations", sa.Integer(), server_default="0", nullable=False
        ),
        sa.Column("money", sa.Integer(), server_default="0", nullable=False),
        sa.Column("current_loan", sa.Integer(), server_default="0", nullable=False),
        sa.Column("income", sa.Integer(), server_default="0", nullable=False),
        sa.Column("delivered", sa.Integer(), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["company.id"],),
        sa.PrimaryKeyConstraint("company_id", "timestamp"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("company_timescale")
    # ### end Alembic commands ###
