"""More vehicle attributes

Revision ID: a96bcd8e69ef
Revises: 30132ebd6c37
Create Date: 2020-06-07 13:21:02.841692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a96bcd8e69ef'
down_revision = '30132ebd6c37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle', sa.Column('max_age', sa.Integer(), nullable=True))
    op.add_column('vehicle', sa.Column('vehicle_type', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicle', 'vehicle_type')
    op.drop_column('vehicle', 'max_age')
    # ### end Alembic commands ###
