"""adding company_id to vehicles

Revision ID: bf1bc44023c3
Revises: 4c549805cdab
Create Date: 2020-06-13 15:51:33.018815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf1bc44023c3'
down_revision = '4c549805cdab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle', sa.Column('company_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicle', 'company_id')
    # ### end Alembic commands ###
