"""Adding more stats

Revision ID: e1d4880587b7
Revises: 209cda7e6ae5
Create Date: 2020-06-06 17:27:52.829730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1d4880587b7'
down_revision = '209cda7e6ae5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('num_lorry', sa.Integer(), server_default='0', nullable=True))
    op.add_column('company', sa.Column('num_lorry_stations', sa.Integer(), server_default='0', nullable=True))
    op.add_column('company', sa.Column('num_plane', sa.Integer(), server_default='0', nullable=True))
    op.add_column('company', sa.Column('num_plane_stations', sa.Integer(), server_default='0', nullable=True))
    op.add_column('company', sa.Column('num_ship', sa.Integer(), server_default='0', nullable=True))
    op.add_column('company', sa.Column('num_ship_stations', sa.Integer(), server_default='0', nullable=True))
    op.add_column('company', sa.Column('num_train', sa.Integer(), server_default='0', nullable=True))
    op.add_column('company', sa.Column('num_train_stations', sa.Integer(), server_default='0', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'num_train_stations')
    op.drop_column('company', 'num_train')
    op.drop_column('company', 'num_ship_stations')
    op.drop_column('company', 'num_ship')
    op.drop_column('company', 'num_plane_stations')
    op.drop_column('company', 'num_plane')
    op.drop_column('company', 'num_lorry_stations')
    op.drop_column('company', 'num_lorry')
    # ### end Alembic commands ###
